//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_GEEK_1                      101
#define IDI_GEEK_2                      102
#define IDD_ABOUT                       103
#define IDD_COMPRESSED_FILE             104
#define IDD_DIPSWITCHES                 105
#define IDD_GAMEGENIE                   106
#define IDD_GAMEGENIE_ADDCODE           107
#define IDD_GRAPHICS                    108
#define IDD_INPUT                       109
#define IDD_INPUT_KEYPRESS              110
#define IDD_PATHS                       111
#define IDD_ROM_INFO                    112
#define IDD_SOUND                       113
#define IDR_MENU                        114
#define IDD_PREFERENCES                 115
#define IDR_ROMDATABASE1                116
#define IDD_AUTO_SAVE                   117
#define IDR_ACCELERATOR                 118
#define IDD_FDS                         119
#define IDD_SOUND_RECORD                120
#define IDD_SOUND_RECORD1               121
#define IDD_MOVIE                       122
#define IDD_LOGFILE                     123
#define IDD_LICENCE                     124
#define IDR_COPYING1                    125
#define IDM_FILE_OPEN                   126
#define IDM_FILE_CLOSE                  127
#define IDM_FILE_LOAD_STATE             128
#define IDM_FILE_SAVE_STATE             129
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_LAST 130
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_1 131
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_2 132
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_3 133
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_4 134
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_5 135
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_6 136
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_7 137
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_8 138
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_9 139
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_NEXT 140
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_1 141
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_2 142
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_3 143
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_4 144
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_5 145
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_6 146
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_7 147
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_8 148
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_9 149
#define IDM_FILE_SAVE_SCREENSHOT        150
#define IDM_FILE_RECORD_SOUND_FILE      151
#define IDM_FILE_RECORD_SOUND_STOP      152
#define IDM_FILE_RECORD_SOUND_RESET     153
#define IDM_FILE_RECORD_SOUND_START     154
#define IDM_FILE_RECENT_0               155
#define IDM_FILE_RECENT_1               156
#define IDM_FILE_RECENT_2               157
#define IDM_FILE_RECENT_3               158
#define IDM_FILE_RECENT_4               159
#define IDM_FILE_RECENT_5               160
#define IDM_FILE_RECENT_6               161
#define IDM_FILE_RECENT_7               162
#define IDM_FILE_RECENT_8               163
#define IDM_FILE_RECENT_9               164
#define IDM_FILE_QUIT                   165
#define IDM_MACHINE_POWER_ON            166
#define IDM_MACHINE_POWER_OFF           167
#define IDM_MACHINE_RESET_SOFT          168
#define IDM_MACHINE_RESET_HARD          169
#define IDM_MACHINE_PORT1_UNCONNECTED   170
#define IDM_MACHINE_PORT1_PAD1          171
#define IDM_MACHINE_PORT1_PAD2          172
#define IDM_MACHINE_PORT1_PAD3          173
#define IDM_MACHINE_PORT1_PAD4          174
#define IDM_MACHINE_PORT1_ZAPPER        175
#define IDM_MACHINE_PORT1_PADDLE        176
#define IDM_MACHINE_PORT1_POWERPAD      177
#define IDM_MACHINE_PORT2_UNCONNECTED   178
#define IDM_MACHINE_PORT2_PAD1          179
#define IDM_MACHINE_PORT2_PAD2          180
#define IDM_MACHINE_PORT2_PAD3          181
#define IDM_MACHINE_PORT2_PAD4          182
#define IDM_MACHINE_PORT2_ZAPPER        183
#define IDM_MACHINE_PORT2_PADDLE        184
#define IDM_MACHINE_PORT2_POWERPAD      185
#define IDM_MACHINE_PORT3_UNCONNECTED   186
#define IDM_MACHINE_PORT3_PAD1          187
#define IDM_MACHINE_PORT3_PAD2          188
#define IDM_MACHINE_PORT3_PAD3          189
#define IDM_MACHINE_PORT3_PAD4          190
#define IDM_MACHINE_PORT4_UNCONNECTED   191
#define IDM_MACHINE_PORT4_PAD1          192
#define IDM_MACHINE_PORT4_PAD2          193
#define IDM_MACHINE_PORT4_PAD3          194
#define IDM_MACHINE_PORT4_PAD4          195
#define IDM_MACHINE_EXPANSION_UNCONNECTED 196
#define IDM_MACHINE_EXPANSION_FAMILYBASICKEYBOARD 197
#define IDM_MACHINE_MODE_NTSC           198
#define IDM_MACHINE_MODE_PAL            199
#define IDM_MACHINE_MODE_AUTO           200
#define IDM_MACHINE_PAUSE               201
#define IDM_VIEW_ROM_INFO               202
#define IDM_VIEW_SWITCH_SCREEN          203
#define IDM_VIEW_NORMAL_WINDOW_SIZE     204
#define IDM_VIEW_HIDE_MENU              205
#define IDM_OPTIONS_VIDEO               206
#define IDM_OPTIONS_SOUND               207
#define IDM_OPTIONS_INPUT               208
#define IDM_OPTIONS_PATHS               209
#define IDM_OPTIONS_GAME_GENIE          210
#define IDM_OPTIONS_DIP_SWITCHES        211
#define IDM_OPTIONS_AUTO_SAVE           212
#define IDM_OPTIONS_PREFERENCES         213
#define IDM_HELP_ABOUT                  214
#define IDM_NSF_PLAY                    215
#define IDM_NSF_STOP                    216
#define IDM_NSF_NEXT                    217
#define IDM_NSF_PREV                    218
#define IDM_FDS_INSERT_DISK_1           219
#define IDM_FDS_INSERT_DISK_2           220
#define IDM_FDS_INSERT_DISK_3           221
#define IDM_FDS_INSERT_DISK_4           222
#define IDM_FDS_INSERT_DISK_5           223
#define IDM_FDS_INSERT_DISK_6           224
#define IDM_FDS_INSERT_DISK_7           225
#define IDM_FDS_INSERT_DISK_8           226
#define IDM_FDS_INSERT_DISK_9           227
#define IDM_FDS_INSERT_DISK_10          228
#define IDM_FDS_INSERT_DISK_11          229
#define IDM_FDS_INSERT_DISK_12          230
#define IDM_FDS_INSERT_DISK_13          231
#define IDM_FDS_INSERT_DISK_14          232
#define IDM_FDS_INSERT_DISK_15          233
#define IDM_FDS_INSERT_DISK_16          234
#define IDM_FDS_EJECT_DISK              235
#define IDM_FDS_SIDE_A                  236
#define IDM_FDS_SIDE_B                  237
#define IDM_FDS_OPTIONS                 238
#define IDM_MACHINE_AUTOSELECTCONTROLLER 239
#define IDM_FILE_MOVIE_FILE             240
#define IDM_FILE_MOVIE_RECORD           241
#define IDM_FILE_MOVIE_PLAY             242
#define IDM_FILE_MOVIE_STOP             243
#define IDM_FILE_MOVIE_REWIND           244
#define IDM_VIEW_LOGFILE                245
#define IDM_HELP_LICENCE                246
#define IDC_SOUND_DEVICE                1001
#define IDC_SOUND_SAMPLE_RATE           1002
#define IDC_SOUND_ENABLE                1003
#define IDC_SOUND_SQUARE1               1004
#define IDC_SOUND_SQUARE2               1005
#define IDC_SOUND_NOISE                 1006
#define IDC_SOUND_TRIANGLE              1007
#define IDC_SOUND_DPCM                  1008
#define IDC_SOUND_EXTERNAL              1009
#define IDC_SOUND_8_BIT                 1010
#define IDC_SOUND_16_BIT                1011
#define IDC_SOUND_LATENCY               1012
#define IDC_SOUND_VOLUME                1013
#define IDC_SOUND_FB1                   1014
#define IDC_SOUND_FB10                  1015
#define IDC_SOUND_V100                  1016
#define IDC_SOUND_V0                    1017
#define IDC_SOUND_DEFAULT               1018
#define IDC_SOUND_OK                    1019
#define IDC_INPUT_DEVICES               1100
#define IDC_INPUT_MAP                   1101
#define IDC_INPUT_KEYS                  1102
#define IDC_INPUT_KEYPRESS_TEXT         1103
#define IDC_INPUT_CLEAR                 1104
#define IDC_INPUT_SET                   1105
#define IDC_INPUT_DEFAULT               1106
#define IDC_INPUT_OK                    1107
#define IDC_PATHS_ROM_IMAGES            1200
#define IDC_PATHS_ROM_IMAGES_LAST       1201
#define IDC_PATHS_ROM_IMAGES_BROWSE     1202
#define IDC_PATHS_SAVE_STATES           1203
#define IDC_PATHS_SAVE_STATES_LAST      1204
#define IDC_PATHS_SAVE_STATES_BROWSE    1205
#define IDC_PATHS_SAVE_RAM              1206
#define IDC_PATHS_SAVE_RAM_LAST         1207
#define IDC_PATHS_IPS                   1207
#define IDC_PATHS_SAVE_RAM_ROM          1208
#define IDC_PATHS_SAVE_RAM_BROWSE       1209
#define IDC_PATHS_DISABLE_SAVERAM_WRITE 1210
#define IDC_PATHS_DEFAULT               1211
#define IDC_PATHS_OK                    1212
#define IDC_PATHS_CANCEL                1213
#define IDC_PATHS_IPS_ROM               1217
#define IDC_PATHS_IPS_BROWSE            1218
#define IDC_COMPRESSED_FILE_LIST        1300
#define IDC_COMPRESSED_FILE_CANCEL      1301
#define IDC_COMPRESSED_FILE_OK          1302
#define IDC_ROM_INFO_EDIT               1400
#define IDC_DIPSWITCHES_1_TEXT          1500
#define IDC_DIPSWITCHES_2_TEXT          1501
#define IDC_DIPSWITCHES_3_TEXT          1502
#define IDC_DIPSWITCHES_4_TEXT          1503
#define IDC_DIPSWITCHES_5_TEXT          1504
#define IDC_DIPSWITCHES_6_TEXT          1505
#define IDC_DIPSWITCHES_7_TEXT          1506
#define IDC_DIPSWITCHES_8_TEXT          1507
#define IDC_DIPSWITCHES_1               1508
#define IDC_DIPSWITCHES_2               1509
#define IDC_DIPSWITCHES_3               1510
#define IDC_DIPSWITCHES_4               1511
#define IDC_DIPSWITCHES_5               1512
#define IDC_DIPSWITCHES_6               1513
#define IDC_DIPSWITCHES_7               1514
#define IDC_DIPSWITCHES_8               1515
#define IDC_DIPSWITCHES_CANCEL          1516
#define IDC_DIPSWITCHES_OK              1517
#define IDC_GRAPHICS_DEVICE             1600
#define IDC_GRAPHICS_MODE               1601
#define IDC_GRAPHICS_16_BIT             1602
#define IDC_GRAPHICS_32_BIT             1603
#define IDC_GRAPHICS_COLORS_HUE         1604
#define IDC_GRAPHICS_COLORS_HUE_TEXT    1605
#define IDC_GRAPHICS_COLORS_HUE_VAL     1606
#define IDC_GRAPHICS_COLORS_SATURATION  1607
#define IDC_GRAPHICS_COLORS_SATURATION_TEXT 1608
#define IDC_GRAPHICS_COLORS_SATURATION_VAL 1609
#define IDC_GRAPHICS_COLORS_BRIGHTNESS  1610
#define IDC_GRAPHICS_COLORS_BRIGHTNESS_TEXT 1611
#define IDC_GRAPHICS_COLORS_BRIGHTNESS_VAL 1612
#define IDC_GRAPHICS_COLORS_RESET       1613
#define IDC_GRAPHICS_EFFECTS            1614
#define IDC_GRAPHICS_SIZE_NORMAL        1615
#define IDC_GRAPHICS_SIZE_STRETCHED     1616
#define IDC_GRAPHICS_SIZE_MATCHED       1617
#define IDC_GRAPHICS_PALETTE_BROWSE     1618
#define IDC_GRAPHICS_PALETTE_PATH       1619
#define IDC_GRAPHICS_PALETTE_CLEAR      1620
#define IDC_GRAPHICS_PALETTE_EMULATED   1621
#define IDC_GRAPHICS_PALETTE_CUSTOM     1622
#define IDC_GRAPHICS_NTSC_TOP           1623
#define IDC_GRAPHICS_NTSC_RIGHT         1624
#define IDC_GRAPHICS_NTSC_BOTTOM        1625
#define IDC_GRAPHICS_NTSC_LEFT          1626
#define IDC_GRAPHICS_PAL_TOP            1627
#define IDC_GRAPHICS_PAL_RIGHT          1628
#define IDC_GRAPHICS_PAL_BOTTOM         1629
#define IDC_GRAPHICS_PAL_LEFT           1630
#define IDC_GRAPHICS_INFINITE_SPRITES   1631
#define IDC_GRAPHICS_SRAM               1632
#define IDC_GRAPHICS_VRAM               1633
#define IDC_GRAPHICS_TIMING_VSYNC       1634
#define IDC_GRAPHICS_TIMING_FRAMESKIP   1635
#define IDC_GRAPHICS_PALETTE_INTERNAL   1636
#define IDC_GRAPHICS_DEFAULT            1637
#define IDC_GRAPHICS_OK                 1638
#define IDC_GAMEGENIE_ADD               1700
#define IDC_GAMEGENIE_REMOVE            1701
#define IDC_GAMEGENIE_IMPORT            1702
#define IDC_GAMEGENIE_EXPORT            1703
#define IDC_GAMEGENIE_CLEAR_ALL         1704
#define IDC_GAMEGENIE_OK                1705
#define IDC_GAMEGENIE_LIST              1706
#define IDC_GAMEGENIE_ADDCODE_ENCODED   1707
#define IDC_GAMEGENIE_ADDCODE_DECODED   1708
#define IDC_GAMEGENIE_ADDCODE_SUBMIT    1709
#define IDC_GAMEGENIE_ADDCODE_CANCEL    1710
#define IDC_GAMEGENIE_ADDCODE_CHARACTERS 1711
#define IDC_GAMEGENIE_ADDCODE_RESULT    1712
#define IDC_GAMEGENIE_ADDCODE_VALUE     1713
#define IDC_GAMEGENIE_ADDCODE_COMPARE   1714
#define IDC_GAMEGENIE_ADDCODE_ADDRESS   1715
#define IDC_GAMEGENIE_ADDCODE_VALIDATE  1716
#define IDC_GAMEGENIE_ADDCODE_COMMENT   1717
#define IDC_PREFERENCES_DEFAULT         1800
#define IDC_PREFERENCES_OK              1801
#define IDC_PREFERENCES_STARTUP_FULLSCREEN 1802
#define IDC_PREFERENCES_DISABLE_ROM_WARNINGS 1803
#define IDC_PREFERENCES_CLOSE_POWER_OFF 1804
#define IDC_PREFERENCES_HIDE_MENU_FULLSCREEN 1805
#define IDC_PREFERENCES_CONFIRM_EXIT    1806
#define IDC_PREFERENCES_RUN_IN_BACKGROUND 1807
#define IDC_PREFERENCES_BEGIN_EMULATION 1808
#define IDC_PREFERENCES_NSF_IN_BACKGROUND 1809
#define IDC_PREFERENCES_LOGFILE         1810
#define IDC_FDS_BROWSE                  1900
#define IDC_FDS_CLEAR                   1901
#define IDC_FDS_BIOS                    1902
#define IDC_FDS_OK                      1903
#define IDC_FDS_CANCEL                  1904
#define IDC_FDS_WRITE_PROTECT           1905
#define HIDC_GRAPHICS_MODE              1999
#define IDC_AUTOSAVE_FILE               2000
#define IDC_AUTOSAVE_BROWSE             2001
#define IDC_AUTOSAVE_TIME               2002
#define IDC_AUTOSAVE_CLEAR              2003
#define IDC_AUTOSAVE_ENABLED            2004
#define IDC_AUTOSAVE_ENABLE_MSG         2005
#define IDC_AUTOSAVE_CANCEL             2006
#define IDC_AUTOSAVE_OK                 2007
#define IDC_PATHS_IPS_AUTO_APPLY        2008
#define IDC_SOUND_RECORD_FILE           2009
#define IDC_SOUND_RECORD_CLEAR          2010
#define IDC_SOUND_RECORD_BROWSE         2011
#define IDC_SOUND_RECORD_CANCEL         2012
#define IDC_SOUND_RECORD_OK             2013
#define IDC_MOVIE_FILE                  2014
#define IDC_MOVIE_CLEAR                 2015
#define IDC_MOVIE_BROWSE                2016
#define IDC_MOVIE_CANCEL                2017
#define IDC_MOVIE_OK                    2018
#define IDC_LOGFILE_CLEAR               2019
#define IDC_LOGFILE_OK                  2020
#define IDC_LOGFILE_EDIT                2021
#define IDC_LICENCE_OK                  2023
#define IDC_LICENCE_EDIT                2024
#define IDC_EMAIL                       2027
#define IDC_ABOUT_URL                   2028
#define IDC_ABOUT_GNU                   2029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        600
#define _APS_NEXT_COMMAND_VALUE         247
#define _APS_NEXT_CONTROL_VALUE         2030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
