//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDR_MENU                        101
#define IDR_LAUNCHER_MENU               102
#define IDR_LAUNCHER_POPUP_MENU         103
#define IDR_ACCELERATOR                 104
#define IDR_COPYING1                    105
#define IDR_ROMDATABASE1                106
#define IDD_ABOUT                       120
#define IDD_COMPRESSED_FILE             121
#define IDD_DIPSWITCHES                 122
#define IDD_GAMEGENIE                   123
#define IDD_GAMEGENIE_ADDCODE           124
#define IDD_GAMEGENIECLOSE              125
#define IDD_GRAPHICS                    126
#define IDD_INPUT                       127
#define IDD_INPUT_KEYPRESS              128
#define IDD_PATHS                       129
#define IDD_ROM_INFO                    130
#define IDD_SOUND                       131
#define IDD_TIMING                      132
#define IDD_PREFERENCES                 133
#define IDD_AUTO_SAVE                   134
#define IDD_FDS                         135
#define IDD_SOUND_RECORD                136
#define IDD_MOVIE                       137
#define IDD_LOGFILE                     138
#define IDD_LICENCE                     139
#define IDD_USERINPUT                   140
#define IDD_FILE_EXIST                  141
#define IDD_LAUNCHER                    142
#define IDD_LAUNCHER_COLUMNSELECT       143
#define IDD_LAUNCHER_PATHS              144
#define IDD_LAUNCHER_FILESEARCH         145
#define IDD_LAUNCHER_COLORS             146
#define IDI_PROGRAM                     180
#define IDI_WINDOW                      181
#define IDI_NES                         182
#define IDI_UNF                         183
#define IDI_FDS                         184
#define IDI_NSF                         185
#define IDI_NSP                         186
#define IDB_FOLDER_CLOSED               190
#define IDB_FOLDER_OPEN                 191
#define IDM_FILE_OPEN                   198
#define IDM_FILE_CLOSE                  199
#define IDM_FILE_LOAD_NSP               200
#define IDM_FILE_LOAD_NST               201
#define IDM_FILE_SAVE_NSP               202
#define IDM_FILE_SAVE_NST               203
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_LAST 204
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_1 205
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_2 206
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_3 207
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_4 208
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_5 209
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_6 210
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_7 211
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_8 212
#define IDM_FILE_QUICK_LOAD_STATE_SLOT_9 213
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_NEXT 214
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_1 215
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_2 216
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_3 217
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_4 218
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_5 219
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_6 220
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_7 221
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_8 222
#define IDM_FILE_QUICK_SAVE_STATE_SLOT_9 223
#define IDM_FILE_SAVE_SCREENSHOT        224
#define IDM_FILE_SOUND_CAPTURE_FILE     225
#define IDM_FILE_SOUND_CAPTURE_STOP     226
#define IDM_FILE_SOUND_CAPTURE_RESET    227
#define IDM_FILE_SOUND_CAPTURE_RECORD   228
#define IDM_FILE_MOVIE_FILE             229
#define IDM_FILE_MOVIE_RECORD           230
#define IDM_FILE_MOVIE_PLAY             231
#define IDM_FILE_MOVIE_STOP             232
#define IDM_FILE_MOVIE_REWIND           233
#define IDM_FILE_MOVIE_FORWARD          234
#define IDM_FILE_RECENT_0               235
#define IDM_FILE_RECENT_1               236
#define IDM_FILE_RECENT_2               237
#define IDM_FILE_RECENT_3               238
#define IDM_FILE_RECENT_4               239
#define IDM_FILE_RECENT_5               240
#define IDM_FILE_RECENT_6               241
#define IDM_FILE_RECENT_7               242
#define IDM_FILE_RECENT_8               243
#define IDM_FILE_RECENT_9               244
#define IDM_FILE_QUIT                   245
#define IDM_MACHINE_POWER_ON            246
#define IDM_MACHINE_POWER_OFF           247
#define IDM_MACHINE_RESET_SOFT          248
#define IDM_MACHINE_RESET_HARD          249
#define IDM_MACHINE_AUTOSELECTCONTROLLER 250
#define IDM_MACHINE_PORT1_UNCONNECTED   251
#define IDM_MACHINE_PORT1_PAD1          252
#define IDM_MACHINE_PORT1_PAD2          253
#define IDM_MACHINE_PORT1_PAD3          254
#define IDM_MACHINE_PORT1_PAD4          255
#define IDM_MACHINE_PORT1_ZAPPER        256
#define IDM_MACHINE_PORT1_PADDLE        257
#define IDM_MACHINE_PORT1_POWERPAD      258
#define IDM_MACHINE_PORT2_UNCONNECTED   259
#define IDM_MACHINE_PORT2_PAD1          260
#define IDM_MACHINE_PORT2_PAD2          261
#define IDM_MACHINE_PORT2_PAD3          262
#define IDM_MACHINE_PORT2_PAD4          263
#define IDM_MACHINE_PORT2_ZAPPER        264
#define IDM_MACHINE_PORT2_PADDLE        265
#define IDM_MACHINE_PORT2_POWERPAD      266
#define IDM_MACHINE_PORT3_UNCONNECTED   267
#define IDM_MACHINE_PORT3_PAD1          268
#define IDM_MACHINE_PORT3_PAD2          269
#define IDM_MACHINE_PORT3_PAD3          270
#define IDM_MACHINE_PORT3_PAD4          271
#define IDM_MACHINE_PORT4_UNCONNECTED   272
#define IDM_MACHINE_PORT4_PAD1          273
#define IDM_MACHINE_PORT4_PAD2          274
#define IDM_MACHINE_PORT4_PAD3          275
#define IDM_MACHINE_PORT4_PAD4          276
#define IDM_MACHINE_EXPANSION_UNCONNECTED 277
#define IDM_MACHINE_EXPANSION_FAMILYBASICKEYBOARD 278
#define IDM_MACHINE_MODE_NTSC           279
#define IDM_MACHINE_MODE_PAL            280
#define IDM_MACHINE_MODE_AUTO           281
#define IDM_MACHINE_PAUSE               282
#define IDM_MACHINE_OPTIONS_UNLIMITEDSPRITES 283
#define IDM_VIEW_ROM_INFO               284
#define IDM_VIEW_SWITCH_SCREEN          285
#define IDM_VIEW_WINDOWSIZE_MAX         286
#define IDM_VIEW_WINDOWSIZE_1X          287
#define IDM_VIEW_WINDOWSIZE_2X          288
#define IDM_VIEW_WINDOWSIZE_4X          289
#define IDM_VIEW_WINDOWSIZE_8X          290
#define IDM_OPTIONS_VIDEO               291
#define IDM_OPTIONS_SOUND               292
#define IDM_OPTIONS_INPUT               293
#define IDM_OPTIONS_TIMING              294
#define IDM_OPTIONS_PATHS               295
#define IDM_OPTIONS_GAME_GENIE          296
#define IDM_OPTIONS_AUTO_SAVE           297
#define IDM_OPTIONS_PREFERENCES         298
#define IDM_HELP_ABOUT                  299
#define IDM_NSF_PLAY                    300
#define IDM_NSF_STOP                    301
#define IDM_NSF_NEXT                    302
#define IDM_NSF_PREV                    303
#define IDM_NSF_OPTIONS_PLAYINBACKGROUND 304
#define IDM_FDS_INSERT_DISK_1           305
#define IDM_FDS_INSERT_DISK_2           306
#define IDM_FDS_INSERT_DISK_3           307
#define IDM_FDS_INSERT_DISK_4           308
#define IDM_FDS_INSERT_DISK_5           309
#define IDM_FDS_INSERT_DISK_6           310
#define IDM_FDS_INSERT_DISK_7           311
#define IDM_FDS_INSERT_DISK_8           312
#define IDM_FDS_INSERT_DISK_9           313
#define IDM_FDS_INSERT_DISK_10          314
#define IDM_FDS_INSERT_DISK_11          315
#define IDM_FDS_INSERT_DISK_12          316
#define IDM_FDS_INSERT_DISK_13          317
#define IDM_FDS_INSERT_DISK_14          318
#define IDM_FDS_INSERT_DISK_15          319
#define IDM_FDS_INSERT_DISK_16          320
#define IDM_FDS_EJECT_DISK              321
#define IDM_FDS_SIDE_A                  322
#define IDM_FDS_SIDE_B                  323
#define IDM_FDS_OPTIONS                 324
#define IDM_VIEW_LOGFILE                325
#define IDM_HELP_LICENCE                326
#define IDM_VIEW_STATUSBAR              327
#define IDM_VIEW_MENU                   328
#define IDM_VIEW_ON_TOP                 329
#define IDM_VIEW_FPS                    330
#define IDM_MACHINE_OPTIONS_DIPSWITCHES 331
#define IDM_LAUNCHER_SHOWGRID           332
#define IDM_LAUNCHER_PATHS              333
#define IDM_LAUNCHER_COLUMNS            334
#define IDM_LAUNCHER_REFRESH            335
#define IDM_LAUNCHER_DATABASECORRECTED  336
#define IDM_LAUNCHER_RUN                337
#define IDM_LAUNCHER_ALIGNCOLUMNS       338
#define IDM_LAUNCHER_POPUP_INSERT       339
#define IDM_LAUNCHER_POPUP_REMOVE       340
#define IDM_LAUNCHER_ADD                341
#define IDM_LAUNCHER_REMOVE             342
#define IDM_LAUNCHER_COLORS             343
#define IDM_FILE_LAUNCHER               345
#define IDM_LAUNCHER_CLEAR_ALL          349
#define IDM_LAUNCHER_FIND               351
#define IDM_NETPLAY_DISCONNECT          359
#define IDM_FILE_NETPLAY                361
#define IDM_NETPLAY_CHATWINDOW          365
#define IDS_APP_CREATEWINDOW_FAILED     604
#define IDS_APP_DETACH_IMAGE            605
#define IDS_APP_EXIT                    606
#define IDS_APP_EXIT_CONFIRM            607
#define IDS_APP_WARNING_TITLE           608
#define IDS_AUTOSAVER_SELECT_NST        609
#define IDS_FDS_BIOS_ZIP_INVALID        610
#define IDS_FDS_LOAD_BIOS               611
#define IDS_FDS_SELECT_BIOS             612
#define IDS_FILE_BITMAP_EXPORT_FAILED   613
#define IDS_FILE_CORRUPT                614
#define IDS_FILE_CREATE_FAILED          615
#define IDS_FILE_IMAGE_NOT_FOUND_1_2    616
#define IDS_FILE_IMAGE_NOT_FOUND_2_2    617
#define IDS_FILE_INVALID                618
#define IDS_FILE_INVALID_NST            619
#define IDS_FILE_IPS_FAILED             620
#define IDS_FILE_LOAD_GAMEGENIE         621
#define IDS_FILE_LOAD_NSP               622
#define IDS_FILE_LOAD_NST               623
#define IDS_FILE_LOAD_PALETTE           624
#define IDS_FILE_NSV_FAILED_1_2         625
#define IDS_FILE_NSV_FAILED_2_2         626
#define IDS_FILE_OPEN                   627
#define IDS_FILE_OPEN_ERROR             628
#define IDS_FILE_PARSE_ERROR            629
#define IDS_FILE_SAVE_BITMAP            630
#define IDS_FILE_SAVE_FAILED            631
#define IDS_FILE_SAVE_GAMEGENIE         632
#define IDS_FILE_SAVE_NSP               633
#define IDS_FILE_SAVE_NST               634
#define IDS_FILE_SAVE_WAVE              635
#define IDS_FILE_SELECT_BATTERY         636
#define IDS_FILE_SELECT_IMAGE           637
#define IDS_FILE_SELECT_IPS             638
#define IDS_FILE_SELECT_MOVIE           639
#define IDS_FILE_SELECT_NSP             640
#define IDS_FILE_SELECT_NST             641
#define IDS_FILE_ZIP_EMPTY              642
#define IDS_FILE_ZIP_TITLE              643
#define IDS_GAMEGENIE_FILE_KEEP_CODES_1_2 644
#define IDS_GAMEGENIE_FILE_KEEP_CODES_2_2 645
#define IDS_FILE_SELECTDIR              646
#define IDS_GAMEGENIE_INVALID           647
#define IDS_GAMEGENIE_INVALID_FILE_1_2  648
#define IDS_GAMEGENIE_INVALID_FILE_2_2  649
#define IDS_INPUT_KEY_RESERVED          650
#define IDS_INPUT_WAIT_KEYPRESS         651
#define IDS_SOUND_DISABLE               652
#define IDS_SOUND_NO_DEVICE             653
#define IDS_SOUNDRECORD_WASTED_SPACE_1_2 654
#define IDS_SOUNDRECORD_WASTED_SPACE_2_2 655
#define IDS_VIDEO_INVALID_DESKTOP_MODE  656
#define IDS_VIDEO_NO_DEVICE             657
#define IDS_VIDEO_NO_DISPLAYMODE        658
#define IDS_APP_REGISTRY_SUCCESS        659
#define IDS_GAMEGENIE_IMPORT_KEEP_1_2   660
#define IDS_GAMEGENIE_TOO_MANY_CODES    661
#define IDS_GAMEGENIE_IMPORT_KEEP_2_2   662
#define IDS_CMDLINE_PARSE_ERROR         663
#define IDS_CFGFILE_PARSE_ERROR         664
#define IDS_FILE_ADD                    665
#define IDS_LAUNCHERFILES_LOAD_ERROR    666
#define IDS_LAUNCHERFILES_SAVE_ERROR    667
#define IDS_APP_MESSAGE                 668
#define IDS_LAUNCHER_SEARCH_TEXT_NOT_FOUND 669
#define IDS_APP_WARNING                 670
#define IDS_APP_ERROR                   671
#define IDS_APP_SEARCH_ERROR            672
#define IDS_APP_UNHANDLED_ERROR         673
#define IDS_LAUNCHER_UNSUPPORTED_RES    674
#define IDS_MACHINE_CONFIRM_RESET       675
#define IDS_MACHINE_CONFIRM_POWER_OFF   676
#define IDS_MACHINE_CONFIRM_DETACH_IMAGE 677
#define IDS_MACHINE_RESET               678
#define IDS_MACHINE_POWER_OFF           679
#define IDS_MACHINE_DETACH_IMAGE        680
#define IDS_NETPLAY_INIT_ERROR          681
#define IDS_NETPLAY_NO_GAMELIST         682
#define IDS_NETPLAY_KAILLERA_ERROR      683
#define IDC_SOUND_DEVICE                1001
#define IDC_SOUND_SAMPLE_RATE           1002
#define IDC_SOUND_ENABLE                1003
#define IDC_SOUND_SQUARE1               1004
#define IDC_SOUND_SQUARE2               1005
#define IDC_SOUND_NOISE                 1006
#define IDC_SOUND_TRIANGLE              1007
#define IDC_SOUND_DPCM                  1008
#define IDC_SOUND_EXTERNAL              1009
#define IDC_SOUND_8_BIT                 1010
#define IDC_SOUND_16_BIT                1011
#define IDC_SOUND_LATENCY               1012
#define IDC_SOUND_VOLUME                1013
#define IDC_SOUND_FB1                   1014
#define IDC_SOUND_FB10                  1015
#define IDC_SOUND_V100                  1016
#define IDC_SOUND_V0                    1017
#define IDC_SOUND_DEFAULT               1018
#define IDC_SOUND_OK                    1019
#define IDC_INPUT_DEVICES               1100
#define IDC_INPUT_MAP                   1101
#define IDC_INPUT_KEYS                  1102
#define IDC_INPUT_KEYPRESS_TEXT         1103
#define IDC_INPUT_CLEAR                 1104
#define IDC_INPUT_SET                   1105
#define IDC_INPUT_DEFAULT               1106
#define IDC_INPUT_OK                    1107
#define IDC_INPUT_SETALL                1108
#define IDC_PATHS_IMAGE                 1200
#define IDC_PATHS_IMAGE_LAST            1201
#define IDC_PATHS_IMAGE_BROWSE          1202
#define IDC_PATHS_NST                   1203
#define IDC_PATHS_NST_LAST              1204
#define IDC_PATHS_NST_BROWSE            1205
#define IDC_PATHS_NST_IN_IMAGE          1206
#define IDC_PATHS_NST_AUTO_IMPORT       1207
#define IDC_PATHS_NST_AUTO_EXPORT       1208
#define IDC_PATHS_BATTERY               1209
#define IDC_PATHS_BATTERY_LAST          1210
#define IDC_PATHS_BATTERY_IN_IMAGE      1211
#define IDC_PATHS_BATTERY_BROWSE        1212
#define IDC_PATHS_BATTERY_PROTECT       1213
#define IDC_PATHS_NSP                   1214
#define IDC_PATHS_NSP_LAST              1215
#define IDC_PATHS_NSP_IN_IMAGE          1216
#define IDC_PATHS_NSP_BROWSE            1217
#define IDC_PATHS_NSP_AUTO_APPLY        1218
#define IDC_PATHS_IPS                   1219
#define IDC_PATHS_IPS_IN_IMAGE          1220
#define IDC_PATHS_IPS_BROWSE            1221
#define IDC_PATHS_IPS_AUTO_APPLY        1222
#define IDC_PATHS_OK                    1223
#define IDC_PATHS_DEFAULT               1224
#define IDC_COMPRESSED_FILE_LIST        1300
#define IDC_COMPRESSED_FILE_CANCEL      1301
#define IDC_COMPRESSED_FILE_OK          1302
#define IDC_ROM_INFO_EDIT               1400
#define IDC_DIPSWITCHES_1_TEXT          1500
#define IDC_DIPSWITCHES_2_TEXT          1501
#define IDC_DIPSWITCHES_3_TEXT          1502
#define IDC_DIPSWITCHES_4_TEXT          1503
#define IDC_DIPSWITCHES_5_TEXT          1504
#define IDC_DIPSWITCHES_6_TEXT          1505
#define IDC_DIPSWITCHES_7_TEXT          1506
#define IDC_DIPSWITCHES_8_TEXT          1507
#define IDC_DIPSWITCHES_1               1508
#define IDC_DIPSWITCHES_2               1509
#define IDC_DIPSWITCHES_3               1510
#define IDC_DIPSWITCHES_4               1511
#define IDC_DIPSWITCHES_5               1512
#define IDC_DIPSWITCHES_6               1513
#define IDC_DIPSWITCHES_7               1514
#define IDC_DIPSWITCHES_8               1515
#define IDC_DIPSWITCHES_CANCEL          1516
#define IDC_DIPSWITCHES_OK              1517
#define IDC_GRAPHICS_DEVICE             1600
#define IDC_GRAPHICS_MODE               1601
#define IDC_GRAPHICS_8_BIT              1602
#define IDC_GRAPHICS_16_BIT             1603
#define IDC_GRAPHICS_32_BIT             1604
#define IDC_GRAPHICS_COLORS_HUE         1605
#define IDC_GRAPHICS_COLORS_HUE_TEXT    1606
#define IDC_GRAPHICS_COLORS_HUE_VAL     1607
#define IDC_GRAPHICS_COLORS_SATURATION  1608
#define IDC_GRAPHICS_COLORS_SATURATION_TEXT 1609
#define IDC_GRAPHICS_COLORS_SATURATION_VAL 1610
#define IDC_GRAPHICS_COLORS_BRIGHTNESS  1611
#define IDC_GRAPHICS_COLORS_BRIGHTNESS_TEXT 1612
#define IDC_GRAPHICS_COLORS_BRIGHTNESS_VAL 1613
#define IDC_GRAPHICS_COLORS_RESET       1614
#define IDC_GRAPHICS_EFFECTS            1615
#define IDC_GRAPHICS_PALETTE_BROWSE     1616
#define IDC_GRAPHICS_PALETTE_PATH       1617
#define IDC_GRAPHICS_PALETTE_CLEAR      1618
#define IDC_GRAPHICS_PALETTE_EMULATED   1619
#define IDC_GRAPHICS_PALETTE_CUSTOM     1620
#define IDC_GRAPHICS_NTSC_TOP           1621
#define IDC_GRAPHICS_NTSC_RIGHT         1622
#define IDC_GRAPHICS_NTSC_BOTTOM        1623
#define IDC_GRAPHICS_NTSC_LEFT          1624
#define IDC_GRAPHICS_PAL_TOP            1625
#define IDC_GRAPHICS_PAL_RIGHT          1626
#define IDC_GRAPHICS_PAL_BOTTOM         1627
#define IDC_GRAPHICS_PAL_LEFT           1628
#define IDC_GRAPHICS_SRAM               1629
#define IDC_GRAPHICS_VRAM               1630
#define IDC_GRAPHICS_PALETTE_INTERNAL   1631
#define IDC_GRAPHICS_DEFAULT            1632
#define IDC_GRAPHICS_OK                 1633
#define IDC_GAMEGENIE_ADD               1700
#define IDC_GAMEGENIE_REMOVE            1701
#define IDC_GAMEGENIE_IMPORT            1702
#define IDC_GAMEGENIE_EXPORT            1703
#define IDC_GAMEGENIE_CLEAR_ALL         1704
#define IDC_GAMEGENIE_OK                1705
#define IDC_GAMEGENIE_LIST              1706
#define IDC_GAMEGENIE_ADDCODE_ENCODED   1707
#define IDC_GAMEGENIE_ADDCODE_DECODED   1708
#define IDC_GAMEGENIE_ADDCODE_SUBMIT    1709
#define IDC_GAMEGENIE_ADDCODE_CANCEL    1710
#define IDC_GAMEGENIE_ADDCODE_CHARACTERS 1711
#define IDC_GAMEGENIE_ADDCODE_RESULT    1712
#define IDC_GAMEGENIE_ADDCODE_VALUE     1713
#define IDC_GAMEGENIE_ADDCODE_COMPARE   1714
#define IDC_GAMEGENIE_ADDCODE_ADDRESS   1715
#define IDC_GAMEGENIE_ADDCODE_VALIDATE  1716
#define IDC_GAMEGENIE_ADDCODE_COMMENT   1717
#define IDC_GAMEGENIECLOSE_REMOVE       1718
#define IDC_GAMEGENIECLOSE_KEEP         1719
#define IDC_GAMEGENIECLOSE_DISABLE      1720
#define IDC_PREFERENCES_DEFAULT         1800
#define IDC_PREFERENCES_OK              1801
#define IDC_PREFERENCES_STARTUP_FULLSCREEN 1802
#define IDC_PREFERENCES_DISABLE_ROM_WARNINGS 1803
#define IDC_PREFERENCES_CLOSE_POWER_OFF 1804
#define IDC_PREFERENCES_CONFIRM_EXIT    1805
#define IDC_PREFERENCES_RUN_IN_BACKGROUND 1806
#define IDC_PREFERENCES_BEGIN_EMULATION 1807
#define IDC_PREFERENCES_SAVE_LOGFILE    1808
#define IDC_PREFERENCES_HIGH_PRIORITY   1809
#define IDC_PREFERENCES_CANCEL          1810
#define IDC_PREFERENCES_USE_ROM_DATABASE 1811
#define IDC_PREFERENCES_MULTIPLE_INSTANCES 1812
#define IDC_PREFERENCES_SAVE_SETTINGS   1813
#define IDC_PREFERENCES_SAVE_LAUNCHER   1814
#define IDC_PREFERENCES_CONFIRM_RESET   1815
#define IDC_FDS_BROWSE                  1900
#define IDC_FDS_CLEAR                   1901
#define IDC_FDS_BIOS                    1902
#define IDC_FDS_OK                      1903
#define IDC_FDS_CANCEL                  1904
#define IDC_FDS_WRITE_PROTECT           1905
#define IDC_AUTOSAVE_FILE               2000
#define IDC_AUTOSAVE_BROWSE             2001
#define IDC_AUTOSAVE_TIME               2002
#define IDC_AUTOSAVE_CLEAR              2003
#define IDC_AUTOSAVE_ENABLED            2004
#define IDC_AUTOSAVE_ENABLE_MSG         2005
#define IDC_AUTOSAVE_CANCEL             2006
#define IDC_AUTOSAVE_OK                 2007
#define IDC_SOUND_CAPTURE_FILE          2100
#define IDC_SOUND_CAPTURE_CLEAR         2101
#define IDC_SOUND_CAPTURE_BROWSE        2102
#define IDC_SOUND_CAPTURE_CANCEL        2103
#define IDC_SOUND_CAPTURE_OK            2104
#define IDC_MOVIE_FILE                  2200
#define IDC_MOVIE_CLEAR                 2201
#define IDC_MOVIE_BROWSE                2202
#define IDC_MOVIE_CANCEL                2203
#define IDC_MOVIE_OK                    2204
#define IDC_LOGFILE_CLEAR               2300
#define IDC_LOGFILE_OK                  2301
#define IDC_LOGFILE_EDIT                2302
#define IDC_LICENCE_OK                  2303
#define IDC_LICENCE_EDIT                2304
#define IDC_ABOUT_URL1                  2400
#define IDC_ABOUT_URL2                  2401
#define IDC_ABOUT_GNU                   2402
#define IDC_USERINPUT_ABORT             2500
#define IDC_USERINPUT_OK                2501
#define IDC_USERINPUT_EDIT              2502
#define IDC_USERINPUT_TEXT              2503
#define IDC_TIMING_SYNC_REFRESH         2600
#define IDC_TIMING_AUTO_FRAME_SKIP      2601
#define IDC_TIMING_VSYNC                2602
#define IDC_TIMING_PFC                  2603
#define IDC_TIMING_FPS                  2604
#define IDC_TIMING_FPS_NUM              2605
#define IDC_TIMING_DEFAULT_FPS          2606
#define IDC_TIMING_FRAME_SKIPS          2607
#define IDC_TIMING_FRAME_SKIPS_NUM      2608
#define IDC_TIMING_FPS_TEXT             2609
#define IDC_TIMING_FRAME_SKIPS_TEXT     2610
#define IDC_TIMING_OK                   2611
#define IDC_TIMING_DEFAULT              2612
#define IDC_PREFERENCES_ASSOCIATE_NES   2700
#define IDC_PREFERENCES_ASSOCIATE_UNF   2701
#define IDC_PREFERENCES_ASSOCIATE_FDS   2702
#define IDC_PREFERENCES_ASSOCIATE_NSF   2703
#define IDC_PREFERENCES_ASSOCIATE_NSP   2704
#define IDC_FILEEXIST_OVERWRITE         2800
#define IDC_FILEEXIST_APPEND            2801
#define IDC_FILEEXIST_CANCEL            2802
#define IDC_LAUNCHER_LIST               2900
#define IDC_LAUNCHER_COLUMNSELECT_OK    2901
#define IDC_LAUNCHER_COLUMNSELECT_CANCEL 2902
#define IDC_LAUNCHER_COLUMNSELECT_SELECTED 2903
#define IDC_LAUNCHER_COLUMNSELECT_AVAILABLE 2904
#define IDC_LAUNCHER_TREE               2905
#define IDC_LAUNCHER_PATHS_LIST         2906
#define IDC_LAUNCHER_PATHS_NES          2907
#define IDC_LAUNCHER_PATHS_UNF          2908
#define IDC_LAUNCHER_PATHS_FDS          2909
#define IDC_LAUNCHER_PATHS_NSF          2910
#define IDC_LAUNCHER_PATHS_NSP          2911
#define IDC_LAUNCHER_PATHS_ADD          2912
#define IDC_LAUNCHER_PATHS_REMOVE       2913
#define IDC_LAUNCHER_PATHS_ZIP          2914
#define IDC_LAUNCHER_PATHS_CLEAR        2915
#define IDC_LAUNCHER_PATHS_ALLFILES     2916
#define IDC_LAUNCHER_PATHS_UNIQUEFILES  2917
#define IDC_LAUNCHER_PATHS_CANCEL       2918
#define IDC_LAUNCHER_PATHS_OK           2919
#define IDC_LAUNCHER_FILESEARCH_ABORT   2920
#define IDC_LAUNCHER_FILESEARCH_FILE    2921
#define IDC_LAUNCHER_COLORS_OK          2922
#define IDC_LAUNCHER_COLORS_DEFAULT     2923
#define IDC_LAUNCHER_COLORS_FG_CHANGE   2924
#define IDC_LAUNCHER_COLORS_BG_CHANGE   2925
#define IDC_LAUNCHER_COLUMNSELECT_DEFAULT 2926
#define IDC_LAUNCHER_COLUMNSELECT_REMOVE 2927
#define IDC_LAUNCHER_COLUMNSELECT_ADD   2928
#define IDC_NETPLAY_START_KAILLERA      2929
#define IDR_NETPLAY_MENU                2930
#define IDC_NETPLAY_GAMELIST            2930
#define IDD_NETPLAY                     2931
#define IDC_NETPLAY_ADD                 2931
#define IDC_NETPLAY_REMOVE              2932
#define IDD_CHAT                        2932
#define IDC_NETPLAY_CANCEL              2933
#define IDC_NETPLAY_CLEAR_ALL           2934
#define IDC_NETPLAY_DEFAULT             2936
#define IDC_CHAT                        2936
#define IDC_NETPLAY_DATABASENAMES       2938
#define IDC_NETPLAY_PLAY_FULLSCREEN     2939

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2933
#define _APS_NEXT_COMMAND_VALUE         366
#define _APS_NEXT_CONTROL_VALUE         2939
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
